/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'mental' : IDL.Null,
  'food' : IDL.Null,
  'exercise' : IDL.Null,
  'routine' : IDL.Null,
});
export const Tip = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
});

export const idlService = IDL.Service({
  'addTip' : IDL.Func([IDL.Text, IDL.Text, Category], [Tip], []),
  'getAllTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
  'getTip' : IDL.Func([IDL.Nat], [Tip], ['query']),
  'getTipsByCategory' : IDL.Func([Category], [IDL.Vec(Tip)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'mental' : IDL.Null,
    'food' : IDL.Null,
    'exercise' : IDL.Null,
    'routine' : IDL.Null,
  });
  const Tip = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
  });
  
  return IDL.Service({
    'addTip' : IDL.Func([IDL.Text, IDL.Text, Category], [Tip], []),
    'getAllTips' : IDL.Func([], [IDL.Vec(Tip)], ['query']),
    'getTip' : IDL.Func([IDL.Nat], [Tip], ['query']),
    'getTipsByCategory' : IDL.Func([Category], [IDL.Vec(Tip)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };